import pytest
from constraints_numeric import validate_phone_pattern

# Auto-generated by TestSuiteGen
# Operation: validate_phone_pattern


class Testvalidatephonepattern:

    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {"phone": "123-456-7890"},
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
            pytest.param(
                "PythonIntentType.REQUIRED_ARG_MISSING",
                {},
                400,
                id="PythonIntentType.REQUIRED_ARG_MISSING",
            ),
            pytest.param(
                "PythonIntentType.NULL_NOT_ALLOWED",
                {"phone": None},
                400,
                id="PythonIntentType.NULL_NOT_ALLOWED",
            ),
            pytest.param(
                "PythonIntentType.PATTERN_MISMATCH",
                {"phone": "!!!invalid_pattern!!!"},
                422,
                id="PythonIntentType.PATTERN_MISMATCH",
            ),
            pytest.param(
                "PythonIntentType.UNEXPECTED_ARGUMENT",
                {"__unexpected_kwarg__": "unexpected_value", "phone": "123-456-7890"},
                400,
                id="PythonIntentType.UNEXPECTED_ARGUMENT",
            ),
        ],
    )
    def test_validate_phone_pattern_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for validate_phone_pattern.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues, ValueError for constraints, or AttributeError for None access
            with pytest.raises((ValueError, TypeError, AssertionError, AttributeError)):
                validate_phone_pattern(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = validate_phone_pattern(**kwargs)
            assert result is not None
