import pytest
from constraints_numeric import validate_username

# Auto-generated by TestSuiteGen
# Operation: validate_username


class Testvalidateusername:
    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {"username": "alice123"},
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
            pytest.param(
                "PythonIntentType.INVALID_USERNAME",
                {"username": "123"},
                400,
                id="PythonIntentType.INVALID_USERNAME",
            ),
            pytest.param(
                "PythonIntentType.INVALID_LENGTH",
                {"username": "a" * 51},
                400,
                id="PythonIntentType.INVALID_LENGTH",
            ),
        ],
    )
    def test_validate_username_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for validate_username.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues or ValueError for constraints
            with pytest.raises((ValueError, TypeError, AssertionError)):
                validate_username(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = validate_username(**kwargs)
            assert result is not None
