import pytest
from constraints_numeric import validate_username

# Auto-generated by TestSuiteGen
# Operation: validate_username


class Testvalidateusername:

    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {"username": "alice123"},
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
            pytest.param(
                "PythonIntentType.REQUIRED_ARG_MISSING",
                {},
                400,
                id="PythonIntentType.REQUIRED_ARG_MISSING",
            ),
            pytest.param(
                "PythonIntentType.NULL_NOT_ALLOWED",
                {"username": None},
                400,
                id="PythonIntentType.NULL_NOT_ALLOWED",
            ),
            pytest.param(
                "PythonIntentType.STRING_TOO_SHORT",
                {"username": "xx"},
                422,
                id="PythonIntentType.STRING_TOO_SHORT",
            ),
            pytest.param(
                "PythonIntentType.EMPTY_STRING",
                {"username": ""},
                422,
                id="PythonIntentType.EMPTY_STRING",
            ),
            pytest.param(
                "PythonIntentType.STRING_TOO_LONG",
                {
                    "username": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
                },
                422,
                id="PythonIntentType.STRING_TOO_LONG",
            ),
            pytest.param(
                "PythonIntentType.UNEXPECTED_ARGUMENT",
                {"__unexpected_kwarg__": "unexpected_value", "username": "alice123"},
                400,
                id="PythonIntentType.UNEXPECTED_ARGUMENT",
            ),
        ],
    )
    def test_validate_username_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for validate_username.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues, ValueError for constraints, or AttributeError for None access
            with pytest.raises((ValueError, TypeError, AssertionError, AttributeError)):
                validate_username(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = validate_username(**kwargs)
            assert result is not None
