import pytest
from constraints_numeric import validate_phone_pattern

# Auto-generated by TestSuiteGen
# Operation: validate_phone_pattern


class Testvalidatephonepattern:
    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {"phone": "123-456-7890"},
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
            pytest.param(
                "PythonIntentType.INVALID_PHONE_FORMAT",
                {"phone": "abc-123-456"},
                400,
                id="PythonIntentType.INVALID_PHONE_FORMAT",
            ),
            pytest.param(
                "PythonIntentType.INVALID_PHONE_LENGTH",
                {"phone": "123456789012"},
                400,
                id="PythonIntentType.INVALID_PHONE_LENGTH",
            ),
        ],
    )
    def test_validate_phone_pattern_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for validate_phone_pattern.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues or ValueError for constraints
            with pytest.raises((ValueError, TypeError, AssertionError)):
                validate_phone_pattern(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = validate_phone_pattern(**kwargs)
            assert result is not None
