import pytest
from constraints_numeric import set_priority, Priority

# Auto-generated by TestSuiteGen
# Operation: set_priority

# Enum mapping for automatic conversion
_ENUM_MAP = {
    "Priority": Priority,
}


class Testsetpriority:

    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {"priority": "LOW", "task_id": "TASK-123"},
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
            pytest.param(
                "PythonIntentType.REQUIRED_ARG_MISSING",
                {"priority": "LOW"},
                400,
                id="PythonIntentType.REQUIRED_ARG_MISSING",
            ),
            pytest.param(
                "PythonIntentType.REQUIRED_ARG_MISSING",
                {"task_id": "TASK-123"},
                400,
                id="PythonIntentType.REQUIRED_ARG_MISSING",
            ),
            pytest.param(
                "PythonIntentType.ENUM_MISMATCH",
                {"priority": "INVALID_ENUM_VALUE", "task_id": "TASK-123"},
                422,
                id="PythonIntentType.ENUM_MISMATCH",
            ),
            pytest.param(
                "PythonIntentType.UNEXPECTED_ARGUMENT",
                {
                    "__unexpected_kwarg__": "unexpected_value",
                    "priority": "LOW",
                    "task_id": "TASK-123",
                },
                400,
                id="PythonIntentType.UNEXPECTED_ARGUMENT",
            ),
        ],
    )
    def test_set_priority_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for set_priority.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Convert enum string values to actual enum instances for HAPPY_PATH
        if expected_status < 400:
            if "priority" in kwargs and isinstance(kwargs["priority"], str):
                try:
                    kwargs["priority"] = Priority(kwargs["priority"].lower())
                except ValueError:
                    pass  # Let the test fail with invalid enum value

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues, ValueError for constraints, or AttributeError for None access
            with pytest.raises((ValueError, TypeError, AssertionError, AttributeError)):
                set_priority(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = set_priority(**kwargs)
            assert result is not None
