import pytest
from constraints_numeric import validate_quantity

# Auto-generated by TestSuiteGen
# Operation: validate_quantity


class Testvalidatequantity:
    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {"quantity": 15},
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
            pytest.param(
                "PythonIntentType.BOUNDARY_MIN_MINUS_ONE",
                {"quantity": 0},
                422,
                id="PythonIntentType.BOUNDARY_MIN_MINUS_ONE",
            ),
            pytest.param(
                "PythonIntentType.NEGATIVE_VALUE",
                {"quantity": -1},
                422,
                id="PythonIntentType.NEGATIVE_VALUE",
            ),
            pytest.param(
                "PythonIntentType.BOUNDARY_MAX_PLUS_ONE",
                {"quantity": 101},
                422,
                id="PythonIntentType.BOUNDARY_MAX_PLUS_ONE",
            ),
        ],
    )
    def test_validate_quantity_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for validate_quantity.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues or ValueError for constraints
            with pytest.raises((ValueError, TypeError, AssertionError)):
                validate_quantity(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = validate_quantity(**kwargs)
            assert result is not None
