import pytest
from constraints_numeric import set_priority

# Auto-generated by TestSuiteGen
# Operation: set_priority


class Testsetpriority:
    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {"task_id": "TASK-123", "priority": "high"},
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
            pytest.param(
                "PythonIntentType.ENUM_MISMATCH",
                {"task_id": "TASK-123", "priority": "INVALID_ENUM_VALUE"},
                422,
                id="PythonIntentType.ENUM_MISMATCH",
            ),
        ],
    )
    def test_set_priority_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for set_priority.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues or ValueError for constraints
            with pytest.raises((ValueError, TypeError, AssertionError)):
                set_priority(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = set_priority(**kwargs)
            assert result is not None
