import { registerUser } from "../src/validator";

// Auto-generated by TestSuiteGen
// Operation: registerUser

const testCases: any[] = [
  {
    intent: "HAPPY_PATH",
    args: {'user': {'username': 'alice123', 'age': 18, 'email': 'alice@example.com', 'bio': 'A passionate software developer.'}},
    expectedStatus: 200,
  },
  {
    intent: "REQUIRED_FIELD_MISSING",
    args: {'user': {'username': 'alice123', 'age': 18, 'email': null, 'bio': 'A passionate software developer.'}},
    expectedStatus: 400,
  },
  {
    intent: "NULL_NOT_ALLOWED",
    args: {'user': {'username': 'alice123', 'age': 18, 'email': '', 'bio': 'A passionate software developer.'}},
    expectedStatus: 400,
  },
  {
    intent: "TYPE_VIOLATION",
    args: {'user': {'username': 'alice123', 'age': 18, 'email': 'alice@example.com', 'bio': 123}},
    expectedStatus: 400,
  },
];

describe("registerUser", () => {
  it.each(testCases)("intent: %s", async (testCase: any) => {
    const { intent, args, expectedStatus } = testCase;

    if (expectedStatus >= 400) {
      await expect(async () => {
        // @ts-ignore
        return await (registerUser)(...Object.values(args));
      }).rejects.toThrow();
    } else {
      // @ts-ignore
      const result = await (registerUser)(...Object.values(args));
      expect(result).toBeDefined();
    }
  });
});