import { validateEmail } from "../src/validator";

// Auto-generated by TestSuiteGen
// Operation: validateEmail

const testCases: any[] = [
  {
    intent: "HAPPY_PATH",
    args: { email: 'alice@example.com' },
    expectedStatus: 200,
  },
  {
    intent: "PATTERN_MISMATCH",
    args: { email: '!!!invalid_pattern!!!' },
    expectedStatus: 400,
  },
];

describe("validateEmail", () => {
  it.each(testCases)("intent: %s", async (testCase: any) => {
    const { intent, args, expectedStatus } = testCase;

    if (expectedStatus >= 400) {
      await expect(async () => {
        // @ts-ignore
        return await (validateEmail)(...Object.values(args));
      }).rejects.toThrow();
    } else {
      // @ts-ignore
      const result = await (validateEmail)(...Object.values(args));
      expect(result).toBeDefined();
    }
  });
});