import { validateAge } from "../src/validator";

// Auto-generated by TestSuiteGen
// Operation: validateAge

const testCases: any[] = [
  {
    intent: "HAPPY_PATH",
    args: {'age': 18},
    expectedStatus: 200,
  },
  {
    intent: "BOUNDARY_MIN_MINUS_ONE",
    args: {'age': 17.99},
    expectedStatus: 400,
  },
];

describe("validateAge", () => {
  it.each(testCases)("intent: %s", async (testCase: any) => {
    const { intent, args, expectedStatus } = testCase;

    if (expectedStatus >= 400) {
      await expect(async () => {
        // @ts-ignore
        return await (validateAge)(...Object.values(args));
      }).rejects.toThrow();
    } else {
      // @ts-ignore
      const result = await (validateAge)(...Object.values(args));
      expect(result).toBeDefined();
    }
  });
});