import { validateUsername } from "../src/validator";

// Auto-generated by TestSuiteGen
// Operation: validateUsername

const testCases: any[] = [
  {
    intent: "HAPPY_PATH",
    args: { username: 'alice123' },
    expectedStatus: 200,
  },
  {
    intent: "STRING_TOO_LONG",
    args: { username: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' },
    expectedStatus: 400,
  },
  {
    intent: "PATTERN_MISMATCH",
    args: { username: '!!!invalid_pattern!!!' },
    expectedStatus: 400,
  },
];

describe("validateUsername", () => {
  it.each(testCases)("intent: %s", async (testCase: any) => {
    const { intent, args, expectedStatus } = testCase;

    if (expectedStatus >= 400) {
      await expect(async () => {
        // @ts-ignore
        return await (validateUsername)(...Object.values(args));
      }).rejects.toThrow();
    } else {
      // @ts-ignore
      const result = await (validateUsername)(...Object.values(args));
      expect(result).toBeDefined();
    }
  });
});