// Uses native fetch (Node.js 18+)
// Auto-generated by TestSuiteGen - Setup is pre-compiled

describe("POST /bookings (create_booking_bookings_post)", () => {
  const BASE_URL = "http://localhost:8006";
  const ENDPOINT = "/bookings";
  const METHOD: string = "POST";  // Typed as string to allow runtime comparisons

  // Operation: create_booking_bookings_post
  // Error Codes Expected: 422

  // Resource tracking for setup/teardown
  const createdResources: Array<{ type: string; id: any; endpoint: string }> = [];
  const placeholders: Record<string, any> = {};

  

  const testCases = [
    /**
     * Verifies successful creation of a booking with valid data.
     */
    {
      intent: "HAPPY_PATH",
      payload: {"attendee_email": "alicesmith@example.com", "attendee_name": "Alice Smith", "event_id": "EVT-1234", "quantity": 1},
      pathParams: {},
      expectedStatus: 201,
    },
    
    /**
     * Verifies validation error when required 'email' field is omitted.
     */
    {
      intent: "REQUIRED_FIELD_MISSING",
      payload: {"attendee_name": "Alice Smith", "event_id": "EVT-1234", "quantity": 1},
      pathParams: {},
      expectedStatus: 422,
    },
    
    /**
     * Verifies validation error when 'email' field contains invalid characters.
     */
    {
      intent: "PATTERN_MISMATCH",
      payload: {"attendee_email": "!!!invalid_pattern!!!", "attendee_name": "Alice Smith", "event_id": "EVT-1234", "quantity": 1},
      pathParams: {},
      expectedStatus: 422,
    },
    
    /**
     * Verifies validation error when 'quantity' field is out of bounds.
     */
    {
      intent: "BOUNDARY_MIN_MINUS_ONE",
      payload: {"attendee_email": "alicesmith@example.com", "attendee_name": "Alice Smith", "event_id": "EVT-1234", "quantity": 0},
      pathParams: {},
      expectedStatus: 422,
    },
    
    /**
     * Verifies validation error when 'quantity' field is out of bounds.
     */
    {
      intent: "BOUNDARY_MAX_PLUS_ONE",
      payload: {"attendee_email": "alicesmith@example.com", "attendee_name": "Alice Smith", "event_id": "EVT-1234", "quantity": 11},
      pathParams: {},
      expectedStatus: 422,
    },
  ];

  it.each(testCases)("intent: %s", async (testCase) => {
    const { intent, payload, pathParams, expectedStatus } = testCase;

    let url = `${BASE_URL}${ENDPOINT}`;

    // Resolve USE_CREATED_RESOURCE placeholders
    // Use Record<string, any> to allow dynamic index access
    const resolvedParams: Record<string, any> = { ...pathParams };
    for (const [name, value] of Object.entries(resolvedParams)) {
      if (typeof value === "string" && value.startsWith("USE_CREATED_RESOURCE")) {
        const resolved = placeholders[value] ?? (createdResources[0]?.id ?? null);
        if (resolved === null) {
          console.warn(`Skipping test: placeholder ${value} not resolved`);
          return; // Skip this test
        }
        resolvedParams[name] = resolved;
      }
    }

    // Replace path parameters in URL
    for (const [name, value] of Object.entries(resolvedParams)) {
      const paramValue =
        value === "__INVALID_TYPE__" ? "invalid_string_value" : value ?? 1;
      url = url.replace(`:${name}`, String(paramValue)).replace(
        `{${name}}`,
        String(paramValue),
      );
    }

    const init: RequestInit = {
      method: METHOD,
      headers: { "Content-Type": "application/json" },
    };

    // Only attach body for methods that support it
    if (payload && ["POST", "PUT", "PATCH"].includes(METHOD)) {
      init.body = JSON.stringify(payload);
    }

    const response = await fetch(url, init);

    expect(response.status).toBe(
      expectedStatus,
    );

    if (expectedStatus >= 400) {
      try {
        const body = await response.json();
        expect(body).toBeDefined();
      } catch {
        // Some error responses might not have JSON body
      }
    }
  });
});

export {};