import pytest
from functional_basic import validate_age

# Auto-generated by TestSuiteGen
# Operation: validate_age


class Testvalidateage:
    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {"age": 1},
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
        ],
    )
    def test_validate_age_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for validate_age.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues or ValueError for constraints
            with pytest.raises((ValueError, TypeError, AssertionError)):
                validate_age(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = validate_age(**kwargs)
            assert result is not None
