import pytest
from security_inputs import _detect_sql_injection

# Auto-generated by TestSuiteGen
# Operation: _detect_sql_injection


class Testdetectsqlinjection:

    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {"field_name": "User Profile", "value": "Secure Data"},
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
            pytest.param(
                "PythonIntentType.REQUIRED_ARG_MISSING",
                {"field_name": "User Profile"},
                400,
                id="PythonIntentType.REQUIRED_ARG_MISSING",
            ),
            pytest.param(
                "PythonIntentType.SQL_INJECTION",
                {"field_name": "User Profile", "value": "' OR '1'='1"},
                422,
                id="PythonIntentType.SQL_INJECTION",
            ),
            pytest.param(
                "PythonIntentType.XSS_INJECTION",
                {"field_name": "User Profile", "value": "<script>alert(1)</script>"},
                422,
                id="PythonIntentType.XSS_INJECTION",
            ),
            pytest.param(
                "PythonIntentType.WHITESPACE_ONLY",
                {"field_name": "User Profile", "value": "   "},
                422,
                id="PythonIntentType.WHITESPACE_ONLY",
            ),
            pytest.param(
                "PythonIntentType.REQUIRED_ARG_MISSING",
                {"value": "Secure Data"},
                400,
                id="PythonIntentType.REQUIRED_ARG_MISSING",
            ),
            pytest.param(
                "PythonIntentType.SQL_INJECTION",
                {"field_name": "' OR '1'='1", "value": "Secure Data"},
                422,
                id="PythonIntentType.SQL_INJECTION",
            ),
            pytest.param(
                "PythonIntentType.XSS_INJECTION",
                {"field_name": "<script>alert(1)</script>", "value": "Secure Data"},
                422,
                id="PythonIntentType.XSS_INJECTION",
            ),
            pytest.param(
                "PythonIntentType.WHITESPACE_ONLY",
                {"field_name": "   ", "value": "Secure Data"},
                422,
                id="PythonIntentType.WHITESPACE_ONLY",
            ),
            pytest.param(
                "PythonIntentType.UNEXPECTED_ARGUMENT",
                {
                    "__unexpected_kwarg__": "unexpected_value",
                    "field_name": "User Profile",
                    "value": "Secure Data",
                },
                400,
                id="PythonIntentType.UNEXPECTED_ARGUMENT",
            ),
        ],
    )
    def test__detect_sql_injection_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for _detect_sql_injection.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues, ValueError for constraints, or AttributeError for None access
            with pytest.raises((ValueError, TypeError, AssertionError, AttributeError)):
                _detect_sql_injection(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = _detect_sql_injection(**kwargs)
            assert result is not None
