import pytest
from security_inputs import _validate_not_empty

# Auto-generated by TestSuiteGen
# Operation: _validate_not_empty


class Testvalidatenotempty:

    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {"field_name": "Sample Field", "value": "Sample Value"},
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
            pytest.param(
                "PythonIntentType.REQUIRED_ARG_MISSING",
                {"field_name": "Sample Field"},
                400,
                id="PythonIntentType.REQUIRED_ARG_MISSING",
            ),
            pytest.param(
                "PythonIntentType.NULL_NOT_ALLOWED",
                {"field_name": "Sample Field", "value": None},
                400,
                id="PythonIntentType.NULL_NOT_ALLOWED",
            ),
            pytest.param(
                "PythonIntentType.REQUIRED_ARG_MISSING",
                {"value": "Sample Value"},
                400,
                id="PythonIntentType.REQUIRED_ARG_MISSING",
            ),
            pytest.param(
                "PythonIntentType.NULL_NOT_ALLOWED",
                {"field_name": None, "value": "Sample Value"},
                400,
                id="PythonIntentType.NULL_NOT_ALLOWED",
            ),
            pytest.param(
                "PythonIntentType.UNEXPECTED_ARGUMENT",
                {
                    "__unexpected_kwarg__": "unexpected_value",
                    "field_name": "Sample Field",
                    "value": "Sample Value",
                },
                400,
                id="PythonIntentType.UNEXPECTED_ARGUMENT",
            ),
        ],
    )
    def test__validate_not_empty_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for _validate_not_empty.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues, ValueError for constraints, or AttributeError for None access
            with pytest.raises((ValueError, TypeError, AssertionError, AttributeError)):
                _validate_not_empty(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = _validate_not_empty(**kwargs)
            assert result is not None
