import pytest
from security_inputs import _sanitize_html

# Auto-generated by TestSuiteGen
# Operation: _sanitize_html


class Testsanitizehtml:

    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {"value": "Sample Text"},
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
            pytest.param(
                "PythonIntentType.REQUIRED_ARG_MISSING",
                {},
                400,
                id="PythonIntentType.REQUIRED_ARG_MISSING",
            ),
            pytest.param(
                "PythonIntentType.SQL_INJECTION",
                {"value": "' OR '1'='1"},
                422,
                id="PythonIntentType.SQL_INJECTION",
            ),
            pytest.param(
                "PythonIntentType.XSS_INJECTION",
                {"value": "<script>alert(1)</script>"},
                422,
                id="PythonIntentType.XSS_INJECTION",
            ),
            pytest.param(
                "PythonIntentType.WHITESPACE_ONLY",
                {"value": "   "},
                422,
                id="PythonIntentType.WHITESPACE_ONLY",
            ),
            pytest.param(
                "PythonIntentType.UNEXPECTED_ARGUMENT",
                {"__unexpected_kwarg__": "unexpected_value", "value": "Sample Text"},
                400,
                id="PythonIntentType.UNEXPECTED_ARGUMENT",
            ),
        ],
    )
    def test__sanitize_html_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for _sanitize_html.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues, ValueError for constraints, or AttributeError for None access
            with pytest.raises((ValueError, TypeError, AssertionError, AttributeError)):
                _sanitize_html(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = _sanitize_html(**kwargs)
            assert result is not None
