import pytest
from security_inputs import search_users

# Auto-generated by TestSuiteGen
# Operation: search_users


class Testsearchusers:

    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {"query": "Search for users"},
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
            pytest.param(
                "PythonIntentType.REQUIRED_ARG_MISSING",
                {},
                400,
                id="PythonIntentType.REQUIRED_ARG_MISSING",
            ),
            pytest.param(
                "PythonIntentType.NULL_NOT_ALLOWED",
                {"query": None},
                400,
                id="PythonIntentType.NULL_NOT_ALLOWED",
            ),
            pytest.param(
                "PythonIntentType.SQL_INJECTION",
                {"query": "' OR '1'='1"},
                422,
                id="PythonIntentType.SQL_INJECTION",
            ),
            pytest.param(
                "PythonIntentType.XSS_INJECTION",
                {"query": "<script>alert(1)</script>"},
                422,
                id="PythonIntentType.XSS_INJECTION",
            ),
            pytest.param(
                "PythonIntentType.WHITESPACE_ONLY",
                {"query": "   "},
                422,
                id="PythonIntentType.WHITESPACE_ONLY",
            ),
            pytest.param(
                "PythonIntentType.UNEXPECTED_ARGUMENT",
                {
                    "__unexpected_kwarg__": "unexpected_value",
                    "query": "Search for users",
                },
                400,
                id="PythonIntentType.UNEXPECTED_ARGUMENT",
            ),
        ],
    )
    def test_search_users_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for search_users.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues, ValueError for constraints, or AttributeError for None access
            with pytest.raises((ValueError, TypeError, AssertionError, AttributeError)):
                search_users(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = search_users(**kwargs)
            assert result is not None
