import pytest
from robustness_edge import calculate_average

# Auto-generated by TestSuiteGen
# Operation: calculate_average


class Testcalculateaverage:

    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {"numbers": [1.0]},
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
            pytest.param(
                "PythonIntentType.INVALID_INPUT",
                {"numbers": "not_a_list"},
                400,
                id="PythonIntentType.INVALID_INPUT",
            ),
            pytest.param(
                "PythonIntentType.INVALID_TYPE",
                {"numbers": ["a", "b"]},
                422,
                id="PythonIntentType.INVALID_TYPE",
            ),
        ],
    )
    def test_calculate_average_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for calculate_average.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues, ValueError for constraints, or AttributeError for None access
            with pytest.raises((ValueError, TypeError, AssertionError, AttributeError)):
                calculate_average(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = calculate_average(**kwargs)
            assert result is not None
