import pytest
from security_inputs import run_script

# Auto-generated by TestSuiteGen
# Operation: run_script


class Testrunscript:
    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {
                    "script_name": "__PLACEHOLDER_STRING_script_name__",
                    "args": "__PLACEHOLDER_STRING_args__",
                },
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
            pytest.param(
                "PythonIntentType.SQL_INJECTION",
                {"script_name": "' OR '1'='1", "args": "__PLACEHOLDER_STRING_args__"},
                422,
                id="PythonIntentType.SQL_INJECTION",
            ),
            pytest.param(
                "PythonIntentType.XSS_INJECTION",
                {
                    "script_name": "<script>alert(1)</script>",
                    "args": "__PLACEHOLDER_STRING_args__",
                },
                422,
                id="PythonIntentType.XSS_INJECTION",
            ),
            pytest.param(
                "PythonIntentType.SQL_INJECTION",
                {
                    "script_name": "__PLACEHOLDER_STRING_script_name__",
                    "args": "' OR '1'='1",
                },
                422,
                id="PythonIntentType.SQL_INJECTION",
            ),
            pytest.param(
                "PythonIntentType.XSS_INJECTION",
                {
                    "script_name": "__PLACEHOLDER_STRING_script_name__",
                    "args": "<script>alert(1)</script>",
                },
                422,
                id="PythonIntentType.XSS_INJECTION",
            ),
        ],
    )
    def test_run_script_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for run_script.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues or ValueError for constraints
            with pytest.raises((ValueError, TypeError, AssertionError)):
                run_script(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = run_script(**kwargs)
            assert result is not None
