import pytest
from security_inputs import search_users

# Auto-generated by TestSuiteGen
# Operation: search_users


class Testsearchusers:
    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {"query": "__PLACEHOLDER_STRING_query__"},
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
            pytest.param(
                "PythonIntentType.SQL_INJECTION",
                {"query": "' OR '1'='1"},
                422,
                id="PythonIntentType.SQL_INJECTION",
            ),
            pytest.param(
                "PythonIntentType.XSS_INJECTION",
                {"query": "<script>alert(1)</script>"},
                422,
                id="PythonIntentType.XSS_INJECTION",
            ),
        ],
    )
    def test_search_users_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for search_users.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues or ValueError for constraints
            with pytest.raises((ValueError, TypeError, AssertionError)):
                search_users(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = search_users(**kwargs)
            assert result is not None
