import {registerUser} from "./src/validator";

// Auto-generated by TestSuiteGen
// Operation: registerUser

const testCases = [
  {
    intent: "HAPPY_PATH",
    args: { user: { username: 'alice123', age: 18, email: 'alice@example.com', bio: 'A passionate software developer.' } },
    expectedStatus: 200,
  },
];

describe("registerUser", () => {
  it.each(testCases)("intent: %s", async (testCase) => {
    const { intent, args, expectedStatus } = testCase;

    if (expectedStatus >= 400) {
      await expect(async () => {
        // @ts-ignore
        return await (registerUser)(...Object.values(args));
      }).rejects.toThrow();
    } else {
      // @ts-ignore
      const result = await (registerUser)(...Object.values(args));
      expect(result).toBeDefined();
    }
  });
});