import pytest
from runtime_traps import build_config_dangerous

# Auto-generated by TestSuiteGen
# Operation: build_config_dangerous


class Testbuildconfigdangerous:
    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {
                    "key": "__PLACEHOLDER_STRING_key__",
                    "value": "__PLACEHOLDER_STRING_value__",
                    "base": {},
                },
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
        ],
    )
    def test_build_config_dangerous_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for build_config_dangerous.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues or ValueError for constraints
            with pytest.raises((ValueError, TypeError, AssertionError)):
                build_config_dangerous(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = build_config_dangerous(**kwargs)
            assert result is not None
