import pytest
from runtime_traps import add_tag_safe

# Auto-generated by TestSuiteGen
# Operation: add_tag_safe


class Testaddtagsafe:

    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {"name": "John Doe", "tags": ["work", "family"]},
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
            pytest.param(
                "PythonIntentType.REQUIRED_ARG_MISSING",
                {"tags": ["work", "family"]},
                400,
                id="PythonIntentType.REQUIRED_ARG_MISSING",
            ),
            pytest.param(
                "PythonIntentType.UNEXPECTED_ARGUMENT",
                {
                    "__unexpected_kwarg__": "unexpected_value",
                    "name": "John Doe",
                    "tags": ["work", "family"],
                },
                400,
                id="PythonIntentType.UNEXPECTED_ARGUMENT",
            ),
        ],
    )
    def test_add_tag_safe_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for add_tag_safe.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues, ValueError for constraints, or AttributeError for None access
            with pytest.raises((ValueError, TypeError, AssertionError, AttributeError)):
                add_tag_safe(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = add_tag_safe(**kwargs)
            assert result is not None
