import pytest
from type_validation import require_non_null

# Auto-generated by TestSuiteGen
# Operation: require_non_null


class Testrequirenonnull:

    @pytest.mark.parametrize(
        "intent, kwargs, expected_status",
        [
            pytest.param(
                "PythonIntentType.HAPPY_PATH",
                {"name": "__PLACEHOLDER_STRING_name__", "age": 1},
                200,
                id="PythonIntentType.HAPPY_PATH",
            ),
            pytest.param(
                "PythonIntentType.NULL_NOT_ALLOWED",
                {"name": None, "age": 1},
                400,
                id="PythonIntentType.NULL_NOT_ALLOWED",
            ),
            pytest.param(
                "PythonIntentType.TYPE_VIOLATION",
                {"name": "__PLACEHOLDER_STRING_name__", "age": "not_an_integer"},
                400,
                id="PythonIntentType.TYPE_VIOLATION",
            ),
            pytest.param(
                "PythonIntentType.NULL_NOT_ALLOWED",
                {"name": "__PLACEHOLDER_STRING_name__", "age": None},
                400,
                id="PythonIntentType.NULL_NOT_ALLOWED",
            ),
        ],
    )
    def test_require_non_null_contract(self, intent, kwargs, expected_status):
        """
        Contract testing for require_non_null.
        Intent: {intent}
        Expected: {expected_status} (400/422 = Exception)
        """

        # Negative Tests (Expect Exceptions)
        if expected_status >= 400:
            # We expect TypeError for structural issues or ValueError for constraints
            with pytest.raises((ValueError, TypeError, AssertionError)):
                require_non_null(**kwargs)

        # Happy Path (Expect Return Value)
        else:
            result = require_non_null(**kwargs)
            assert result is not None
